### ISSUE TITLE
pidfile issue

### ISSUE THREAD

**Issue by mfournier** [camptocamp/puppet-carbon#4]
carbon cache instances write their pidfile in `/var/run/carbon`, `/var/run` is a ramdisk, so the "carbon" subdir doesn't exist anymore after a reboot.

**Comment by mfournier** [comment]
`Sep 16 17:43:57 metrics carbon-cache[8505]: 16/09/2015 17:43:57 :: [console] /usr/lib/python2.7/dist-packages/twisted/python/util.py:753: exceptions.UserWarning: tried to drop privileges and setuid 106 but uid is already 106; should we be root? Continuing.`

Maybe simply starting the service as root (and moving the pidfiles to `/var/run`) is enough to fix the issue ? ^

**Comment by diegobill** [comment]
+1 Same problem

**Comment by mfournier** [comment]
@diegobill FYI this issued was fixed in 0.1.7. Thanks !
